export const ADD_SONG_START = 'ADD_SONG';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILURE= 'ADD_SONG_FAILURE';

export const GET_SONGS_START = 'GET_SONGS_START';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAILURE = 'GET_SONGS_FAILURE';

export const PLAY_SONG_START = 'PLAY_SONG';
export const PLAY_SONG_SUCCESS = 'PLAY_SONG_SUCCESS';
export const PLAY_SONG_FAILURE = 'PLAY_SONG_FAILURE';
