export const ADD_SONG_START = 'ADD_SONG';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILURE= 'ADD_SONG_FAILURE';

export const GET_SONGS_START = 'GET_SONGS_START';
export const GET_SONGS_SUCCESS = 'GET_SONGS_SUCCESS';
export const GET_SONGS_FAILURE = 'GET_SONGS_FAILURE';

export const DELETE_SONG_START = 'DELETE_SONG_START';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILURE = 'DELETE_SONG_FAILURE';
